//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPQC_CHECKING_SYSTEM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPQC
    {
        public string PartNumber { get; set; }
        public string Type { get; set; }
        public string SubmitPIC { get; set; }
        public string IPQC1 { get; set; }
        public string TimeSubmit { get; set; }
        public string TimeRecive { get; set; }
        public string ReleaseTime { get; set; }
        public string CheckingTime { get; set; }
        public string TotalTime { get; set; }
        public string Result { get; set; }
        public string Status { get; set; }

    }
}
